---
- name: Ensure dependencies are installed.
  apt:
    name: apt-transport-https
    state: present

- name: Add Plex Media Server apt repository key.
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: Add Plex apt repository.
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present
    update_cache: true

- name: Ensure Plex Media Server is installed.
  apt:
    name: plexmediaserver
    state: present
    update_cache: true
  notify: restart plex

- name: Create the Plex Media Server config directory
  file:
    path: /etc/systemd/system/plexmediaserver.service.d
    state: directory
    owner: root
    group: root

- name: Configure Plex Media Server.
  template:
    src: plex-service-override.conf.j2
    dest: /etc/systemd/system/plexmediaserver.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify: restart plex

- name: Ensure the Plex Media Server app support dir exists with the correct permissions.
  file:
    path: "{{ plex_app_support_dir }}"
    state: directory
    owner: "{{ plex_service_user }}"
    group: "{{ plex_service_group }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes
  notify: restart plex

- name: Ensure the /var/lib/plexmediaserver dir has the correct permissions.
  file:
    path: /var/lib/plexmediaserver
    state: directory
    owner: "{{ plex_service_user }}"
    group: "{{ plex_service_group }}"
  notify: restart plex

- name: Ensure Plex Media Server autostarts.
  service:
    name: plexmediaserver
    enabled: true
  notify: restart plex
